services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
